// Code generated by smithy-go-codegen DO NOT EDIT.


package types

import (
	smithydocument "github.com/aws/smithy-go/document"
)

type DockerParameters struct {
	
	DisableCache *bool
	
	DisableEntrypointOverwrite *bool
	
	ExtraHosts []ExtraHosts
	
	Image *string
	
	OomKillDisable *bool
	
	Privileged *bool
	
	ShmSize *int32
	
	TlsVerify *bool
	
	Volumes []string
	
	noSmithyDocumentSerde
}

type ExtraHosts struct {
	
	HostName *string
	
	IpAddress *string
	
	noSmithyDocumentSerde
}

type NetworkConfig struct {
	
	NetworkId *string
	
	PrivateAddress *string
	
	noSmithyDocumentSerde
}

type ParameterGroup struct {
	
	CreateTime *string
	
	Description *string
	
	DockerParameters *DockerParameters
	
	ParameterGroupName *string
	
	Region *string
	
	RunnerNames []string
	
	noSmithyDocumentSerde
}

type ParameterGroups struct {
	
	CreateTime *string
	
	Description *string
	
	DockerParameters *DockerParameters
	
	ParameterGroupName *string
	
	Region *string
	
	RunnerNames []string
	
	noSmithyDocumentSerde
}

type Registrations struct {
	
	GitlabUrl *string
	
	ParameterGroupName *string
	
	RegistrationId *string
	
	Status *Status
	
	Token *string
	
	noSmithyDocumentSerde
}

type RequestDockerParameters struct {
	
	DisableCache *bool
	
	DisableEntrypointOverwrite *bool
	
	Image *string
	
	ListOfRequestExtraHosts []RequestExtraHosts
	
	ListOfRequestVolumes []string
	
	OomKillDisable *bool
	
	Privileged *bool
	
	ShmSize *int32
	
	TlsVerify *bool
	
	noSmithyDocumentSerde
}

type RequestExtraHosts struct {
	
	HostName *string
	
	IpAddress *string
	
	noSmithyDocumentSerde
}

type RequestNetworkConfig struct {
	
	NetworkId *string
	
	PrivateAddress *string
	
	noSmithyDocumentSerde
}

type Runner struct {
	
	AvailabilityZone *string
	
	Concurrent *int32
	
	CreateTime *string
	
	Description *string
	
	InstanceType *string
	
	NetworkConfig *NetworkConfig
	
	PublicIpAddress *string
	
	Region *string
	
	RunnerName *string
	
	RunnerVersion *string
	
	Status *Status
	
	SystemId *string
	
	noSmithyDocumentSerde
}

type Runners struct {
	
	AvailabilityZone *string
	
	Concurrent *int32
	
	CreateTime *string
	
	Description *string
	
	InstanceType *string
	
	NetworkConfig *NetworkConfig
	
	PublicIpAddress *string
	
	Region *string
	
	RunnerName *string
	
	RunnerVersion *string
	
	Status *Status
	
	SystemId *string
	
	noSmithyDocumentSerde
}

type Status struct {
	
	Code *int32
	
	Name *string
	
	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
