// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package hatoba

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/private/protocol"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type DeleteClustersInput struct {
	_ struct{} `type:"structure"`

	// Names is a required field
	Names *string `location:"querystring" locationName:"names" type:"string" required:"true"`
}

// String returns the string representation
func (s DeleteClustersInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DeleteClustersInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "DeleteClustersInput"}

	if s.Names == nil {
		invalidParams.Add(aws.NewErrParamRequired("Names"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

// MarshalFields encodes the AWS API shape using the passed in protocol encoder.
func (s DeleteClustersInput) MarshalFields(e protocol.FieldEncoder) error {
	e.SetValue(protocol.HeaderTarget, "Content-Type", protocol.StringValue("application/json"), protocol.Metadata{})

	if s.Names != nil {
		v := *s.Names

		metadata := protocol.Metadata{}
		e.SetValue(protocol.QueryTarget, "names", protocol.QuotedValue{ValueMarshaler: protocol.StringValue(v)}, metadata)
	}
	return nil
}

type DeleteClustersOutput struct {
	_ struct{} `type:"structure"`

	Clusters []Clusters `locationName:"clusters" type:"list"`
}

// String returns the string representation
func (s DeleteClustersOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// MarshalFields encodes the AWS API shape using the passed in protocol encoder.
func (s DeleteClustersOutput) MarshalFields(e protocol.FieldEncoder) error {
	if s.Clusters != nil {
		v := s.Clusters

		metadata := protocol.Metadata{}
		ls0 := e.List(protocol.BodyTarget, "clusters", metadata)
		ls0.Start()
		for _, v1 := range v {
			ls0.ListAddFields(v1)
		}
		ls0.End()

	}
	return nil
}

const opDeleteClusters = "DeleteClusters"

// DeleteClustersRequest returns a request value for making API operation for
// NIFCLOUD Kubernetes Service Hatoba.
//
//    // Example sending a request using DeleteClustersRequest.
//    req := client.DeleteClustersRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/hatoba/DeleteClusters.htm
func (c *Client) DeleteClustersRequest(input *DeleteClustersInput) DeleteClustersRequest {
	op := &aws.Operation{
		Name:       opDeleteClusters,
		HTTPMethod: "DELETE",
		HTTPPath:   "/v1/clusters",
	}

	if input == nil {
		input = &DeleteClustersInput{}
	}

	req := c.newRequest(op, input, &DeleteClustersOutput{})

	return DeleteClustersRequest{Request: req, Input: input, Copy: c.DeleteClustersRequest}
}

// DeleteClustersRequest is the request type for the
// DeleteClusters API operation.
type DeleteClustersRequest struct {
	*aws.Request
	Input *DeleteClustersInput
	Copy  func(*DeleteClustersInput) DeleteClustersRequest
}

// Send marshals and sends the DeleteClusters API request.
func (r DeleteClustersRequest) Send(ctx context.Context) (*DeleteClustersResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DeleteClustersResponse{
		DeleteClustersOutput: r.Request.Data.(*DeleteClustersOutput),
		response:             &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DeleteClustersResponse is the response type for the
// DeleteClusters API operation.
type DeleteClustersResponse struct {
	*DeleteClustersOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DeleteClusters request.
func (r *DeleteClustersResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
