// Code generated by smithy-go-codegen DO NOT EDIT.


package types

import (
	smithydocument "github.com/aws/smithy-go/document"
	"time"
)

type Datapoints struct {
	
	SampleCount *int32
	
	Sum *float64
	
	TargetName *string
	
	Timestamp *time.Time
	
	noSmithyDocumentSerde
}

type DomainControllers struct {
	
	Hostname *string
	
	IPAddress *string
	
	noSmithyDocumentSerde
}

type Endpoint struct {
	
	Address *string
	
	PrivateAddress *string
	
	noSmithyDocumentSerde
}

type IPRanges struct {
	
	CIDRIP *string
	
	Status *string
	
	noSmithyDocumentSerde
}

type NASInstance struct {
	
	AllocatedStorage *int32
	
	AuthenticationType *int32
	
	AvailabilityZone *string
	
	DirectoryServiceDomainName *string
	
	DomainControllers []DomainControllers
	
	Endpoint *Endpoint
	
	MasterUsername *string
	
	NASInstanceClass *string
	
	NASInstanceDescription *string
	
	NASInstanceErrorInfo *NASInstanceErrorInfo
	
	NASInstanceIdentifier *string
	
	NASInstanceStatus *string
	
	NASInstanceType *int32
	
	NASSecurityGroups []NASSecurityGroups
	
	NetworkId *string
	
	NoRootSquash *bool
	
	Protocol *string
	
	StorageType *int32
	
	UpgradeRequired *bool
	
	noSmithyDocumentSerde
}

type NASInstanceErrorInfo struct {
	
	NASInstanceErrorCode *string
	
	NASInstanceErrorMessage *string
	
	noSmithyDocumentSerde
}

type NASInstances struct {
	
	AllocatedStorage *int32
	
	AuthenticationType *int32
	
	AvailabilityZone *string
	
	DirectoryServiceDomainName *string
	
	DomainControllers []DomainControllers
	
	Endpoint *Endpoint
	
	MasterUsername *string
	
	NASInstanceClass *string
	
	NASInstanceDescription *string
	
	NASInstanceErrorInfo *NASInstanceErrorInfo
	
	NASInstanceIdentifier *string
	
	NASInstanceStatus *string
	
	NASInstanceType *int32
	
	NASSecurityGroups []NASSecurityGroups
	
	NetworkId *string
	
	NoRootSquash *bool
	
	Protocol *string
	
	StorageType *int32
	
	UpgradeRequired *bool
	
	noSmithyDocumentSerde
}

type NASSecurityGroup struct {
	
	AvailabilityZone *string
	
	IPRanges []IPRanges
	
	NASSecurityGroupDescription *string
	
	NASSecurityGroupName *string
	
	OwnerId *string
	
	SecurityGroups []SecurityGroups
	
	noSmithyDocumentSerde
}

type NASSecurityGroups struct {
	
	NASSecurityGroupName *string
	
	Status *string
	
	noSmithyDocumentSerde
}

type NASSecurityGroupsOfDescribeNASSecurityGroups struct {
	
	AvailabilityZone *string
	
	IPRanges []IPRanges
	
	NASSecurityGroupDescription *string
	
	NASSecurityGroupName *string
	
	OwnerId *string
	
	SecurityGroups []SecurityGroups
	
	noSmithyDocumentSerde
}

type RequestDimensions struct {
	
	// This member is required.
	Name *string
	
	// This member is required.
	Value *string
	
	noSmithyDocumentSerde
}

type RequestDomainControllers struct {
	
	Hostname *string
	
	IPAddress *string
	
	noSmithyDocumentSerde
}

type ResponseMetadata struct {
	
	RequestId *string
	
	noSmithyDocumentSerde
}

type SecurityGroups struct {
	
	SecurityGroupName *string
	
	SecurityGroupOwnerId *string
	
	Status *string
	
	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
