// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package nas

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type GetMetricStatisticsInput struct {
	_ struct{} `type:"structure"`

	// Dimensions is a required field
	Dimensions []RequestDimensions `locationName:"Dimensions" locationNameList:"member" type:"list" required:"true"`

	EndTime *time.Time `locationName:"EndTime" type:"timestamp"`

	// MetricName is a required field
	MetricName MetricNameOfGetMetricStatisticsRequest `locationName:"MetricName" type:"string" required:"true" enum:"true"`

	StartTime *time.Time `locationName:"StartTime" type:"timestamp"`
}

// String returns the string representation
func (s GetMetricStatisticsInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *GetMetricStatisticsInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "GetMetricStatisticsInput"}

	if s.Dimensions == nil {
		invalidParams.Add(aws.NewErrParamRequired("Dimensions"))
	}
	if len(s.MetricName) == 0 {
		invalidParams.Add(aws.NewErrParamRequired("MetricName"))
	}
	if s.Dimensions != nil {
		for i, v := range s.Dimensions {
			if err := v.Validate(); err != nil {
				invalidParams.AddNested(fmt.Sprintf("%s[%v]", "Dimensions", i), err.(aws.ErrInvalidParams))
			}
		}
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type GetMetricStatisticsOutput struct {
	_ struct{} `type:"structure"`

	Datapoints []Datapoints `locationName:"Datapoints" locationNameList:"member" type:"list"`

	Label *string `locationName:"Label" type:"string"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`
}

// String returns the string representation
func (s GetMetricStatisticsOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opGetMetricStatistics = "GetMetricStatistics"

// GetMetricStatisticsRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using GetMetricStatisticsRequest.
//    req := client.GetMetricStatisticsRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/nas/GetMetricStatistics.htm
func (c *Client) GetMetricStatisticsRequest(input *GetMetricStatisticsInput) GetMetricStatisticsRequest {
	op := &aws.Operation{
		Name:       opGetMetricStatistics,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetMetricStatisticsInput{}
	}

	req := c.newRequest(op, input, &GetMetricStatisticsOutput{})

	return GetMetricStatisticsRequest{Request: req, Input: input, Copy: c.GetMetricStatisticsRequest}
}

// GetMetricStatisticsRequest is the request type for the
// GetMetricStatistics API operation.
type GetMetricStatisticsRequest struct {
	*aws.Request
	Input *GetMetricStatisticsInput
	Copy  func(*GetMetricStatisticsInput) GetMetricStatisticsRequest
}

// Send marshals and sends the GetMetricStatistics API request.
func (r GetMetricStatisticsRequest) Send(ctx context.Context) (*GetMetricStatisticsResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &GetMetricStatisticsResponse{
		GetMetricStatisticsOutput: r.Request.Data.(*GetMetricStatisticsOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// GetMetricStatisticsResponse is the response type for the
// GetMetricStatistics API operation.
type GetMetricStatisticsResponse struct {
	*GetMetricStatisticsOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// GetMetricStatistics request.
func (r *GetMetricStatisticsResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
