// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package dnsiface provides an interface to enable mocking the NIFCLOUD DNS service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package dnsiface

import (
	"github.com/nifcloud/nifcloud-sdk-go/service/dns"
)

// ClientAPI provides an interface to enable mocking the
// dns.Client methods. This make unit testing your code that
// calls out to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // dns.
//    func myFunc(svc dnsiface.ClientAPI) bool {
//        // Make svc.ChangeResourceRecordSets request
//    }
//
//    func main() {
//        cfg, err := external.LoadDefaultAWSConfig()
//        if err != nil {
//            panic("failed to load config, " + err.Error())
//        }
//
//        svc := dns.New(cfg)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockClientClient struct {
//        dnsiface.ClientPI
//    }
//    func (m *mockClientClient) ChangeResourceRecordSets(input *dns.ChangeResourceRecordSetsInput) (*dns.ChangeResourceRecordSetsOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockClientClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type ClientAPI interface {
	ChangeResourceRecordSetsRequest(*dns.ChangeResourceRecordSetsInput) dns.ChangeResourceRecordSetsRequest

	CreateHostedZoneRequest(*dns.CreateHostedZoneInput) dns.CreateHostedZoneRequest

	DeleteHostedZoneRequest(*dns.DeleteHostedZoneInput) dns.DeleteHostedZoneRequest

	GetChangeRequest(*dns.GetChangeInput) dns.GetChangeRequest

	GetHostedZoneRequest(*dns.GetHostedZoneInput) dns.GetHostedZoneRequest

	ListHostedZonesRequest(*dns.ListHostedZonesInput) dns.ListHostedZonesRequest

	ListResourceRecordSetsRequest(*dns.ListResourceRecordSetsInput) dns.ListResourceRecordSetsRequest
}

var _ ClientAPI = (*dns.Client)(nil)
