// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package rdb

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type CreateDBSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	DBSecurityGroupDescription *string `locationName:"DBSecurityGroupDescription" type:"string"`

	DBSecurityGroupName *string `locationName:"DBSecurityGroupName" type:"string"`

	NiftyAvailabilityZone *string `locationName:"NiftyAvailabilityZone" type:"string"`
}

// String returns the string representation
func (s CreateDBSecurityGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

type CreateDBSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	DBSecurityGroup *DBSecurityGroup `type:"structure"`
}

// String returns the string representation
func (s CreateDBSecurityGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opCreateDBSecurityGroup = "CreateDBSecurityGroup"

// CreateDBSecurityGroupRequest returns a request value for making API operation for
// NIFCLOUD RDB.
//
//    // Example sending a request using CreateDBSecurityGroupRequest.
//    req := client.CreateDBSecurityGroupRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rdb/CreateDBSecurityGroup.htm
func (c *Client) CreateDBSecurityGroupRequest(input *CreateDBSecurityGroupInput) CreateDBSecurityGroupRequest {
	op := &aws.Operation{
		Name:       opCreateDBSecurityGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateDBSecurityGroupInput{}
	}

	req := c.newRequest(op, input, &CreateDBSecurityGroupOutput{})

	return CreateDBSecurityGroupRequest{Request: req, Input: input, Copy: c.CreateDBSecurityGroupRequest}
}

// CreateDBSecurityGroupRequest is the request type for the
// CreateDBSecurityGroup API operation.
type CreateDBSecurityGroupRequest struct {
	*aws.Request
	Input *CreateDBSecurityGroupInput
	Copy  func(*CreateDBSecurityGroupInput) CreateDBSecurityGroupRequest
}

// Send marshals and sends the CreateDBSecurityGroup API request.
func (r CreateDBSecurityGroupRequest) Send(ctx context.Context) (*CreateDBSecurityGroupResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &CreateDBSecurityGroupResponse{
		CreateDBSecurityGroupOutput: r.Request.Data.(*CreateDBSecurityGroupOutput),
		response:                    &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// CreateDBSecurityGroupResponse is the response type for the
// CreateDBSecurityGroup API operation.
type CreateDBSecurityGroupResponse struct {
	*CreateDBSecurityGroupOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// CreateDBSecurityGroup request.
func (r *CreateDBSecurityGroupResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
