// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package rdb

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type RestoreDBInstanceFromDBSnapshotInput struct {
	_ struct{} `type:"structure"`

	AccountingType AccountingTypeOfRestoreDBInstanceFromDBSnapshotRequest `locationName:"AccountingType" type:"string" enum:"true"`

	AutoMinorVersionUpgrade *bool `locationName:"AutoMinorVersionUpgrade" type:"boolean"`

	AvailabilityZone *string `locationName:"AvailabilityZone" type:"string"`

	// DBInstanceClass is a required field
	DBInstanceClass DBInstanceClassOfRestoreDBInstanceFromDBSnapshotRequest `locationName:"DBInstanceClass" type:"string" required:"true" enum:"true"`

	// DBInstanceIdentifier is a required field
	DBInstanceIdentifier *string `locationName:"DBInstanceIdentifier" type:"string" required:"true"`

	DBName *string `locationName:"DBName" type:"string"`

	// DBSnapshotIdentifier is a required field
	DBSnapshotIdentifier *string `locationName:"DBSnapshotIdentifier" type:"string" required:"true"`

	DBSubnetGroupName *string `locationName:"DBSubnetGroupName" type:"string"`

	Engine *string `locationName:"Engine" type:"string"`

	Iops *int64 `locationName:"Iops" type:"integer"`

	LicenseModel *string `locationName:"LicenseModel" type:"string"`

	MultiAZ *bool `locationName:"MultiAZ" type:"boolean"`

	NiftyDBParameterGroupName *string `locationName:"NiftyDBParameterGroupName" type:"string"`

	NiftyDBSecurityGroups []string `locationName:"NiftyDBSecurityGroups" locationNameList:"member" type:"list"`

	NiftyMasterPrivateAddress *string `locationName:"NiftyMasterPrivateAddress" type:"string"`

	NiftyMultiAZType *int64 `locationName:"NiftyMultiAZType" type:"integer"`

	NiftyNetworkId *string `locationName:"NiftyNetworkId" type:"string"`

	NiftyReadReplicaDBInstanceIdentifier *string `locationName:"NiftyReadReplicaDBInstanceIdentifier" type:"string"`

	NiftyReadReplicaPrivateAddress *string `locationName:"NiftyReadReplicaPrivateAddress" type:"string"`

	NiftySlavePrivateAddress *string `locationName:"NiftySlavePrivateAddress" type:"string"`

	NiftyStorageType *int64 `locationName:"NiftyStorageType" type:"integer"`

	NiftyVirtualPrivateAddress *string `locationName:"NiftyVirtualPrivateAddress" type:"string"`

	OptionGroupName *string `locationName:"OptionGroupName" type:"string"`

	Port *int64 `locationName:"Port" type:"integer"`

	PubliclyAccessible *bool `locationName:"PubliclyAccessible" type:"boolean"`

	ReadReplicaAccountingType ReadReplicaAccountingTypeOfRestoreDBInstanceFromDBSnapshotRequest `locationName:"ReadReplicaAccountingType" type:"string" enum:"true"`
}

// String returns the string representation
func (s RestoreDBInstanceFromDBSnapshotInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *RestoreDBInstanceFromDBSnapshotInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "RestoreDBInstanceFromDBSnapshotInput"}
	if len(s.DBInstanceClass) == 0 {
		invalidParams.Add(aws.NewErrParamRequired("DBInstanceClass"))
	}

	if s.DBInstanceIdentifier == nil {
		invalidParams.Add(aws.NewErrParamRequired("DBInstanceIdentifier"))
	}

	if s.DBSnapshotIdentifier == nil {
		invalidParams.Add(aws.NewErrParamRequired("DBSnapshotIdentifier"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type RestoreDBInstanceFromDBSnapshotOutput struct {
	_ struct{} `type:"structure"`

	DBInstance *DBInstance `locationName:"DBInstance" type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`
}

// String returns the string representation
func (s RestoreDBInstanceFromDBSnapshotOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opRestoreDBInstanceFromDBSnapshot = "RestoreDBInstanceFromDBSnapshot"

// RestoreDBInstanceFromDBSnapshotRequest returns a request value for making API operation for
// NIFCLOUD RDB.
//
//    // Example sending a request using RestoreDBInstanceFromDBSnapshotRequest.
//    req := client.RestoreDBInstanceFromDBSnapshotRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rdb/RestoreDBInstanceFromDBSnapshot.htm
func (c *Client) RestoreDBInstanceFromDBSnapshotRequest(input *RestoreDBInstanceFromDBSnapshotInput) RestoreDBInstanceFromDBSnapshotRequest {
	op := &aws.Operation{
		Name:       opRestoreDBInstanceFromDBSnapshot,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &RestoreDBInstanceFromDBSnapshotInput{}
	}

	req := c.newRequest(op, input, &RestoreDBInstanceFromDBSnapshotOutput{})

	return RestoreDBInstanceFromDBSnapshotRequest{Request: req, Input: input, Copy: c.RestoreDBInstanceFromDBSnapshotRequest}
}

// RestoreDBInstanceFromDBSnapshotRequest is the request type for the
// RestoreDBInstanceFromDBSnapshot API operation.
type RestoreDBInstanceFromDBSnapshotRequest struct {
	*aws.Request
	Input *RestoreDBInstanceFromDBSnapshotInput
	Copy  func(*RestoreDBInstanceFromDBSnapshotInput) RestoreDBInstanceFromDBSnapshotRequest
}

// Send marshals and sends the RestoreDBInstanceFromDBSnapshot API request.
func (r RestoreDBInstanceFromDBSnapshotRequest) Send(ctx context.Context) (*RestoreDBInstanceFromDBSnapshotResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &RestoreDBInstanceFromDBSnapshotResponse{
		RestoreDBInstanceFromDBSnapshotOutput: r.Request.Data.(*RestoreDBInstanceFromDBSnapshotOutput),
		response:                              &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// RestoreDBInstanceFromDBSnapshotResponse is the response type for the
// RestoreDBInstanceFromDBSnapshot API operation.
type RestoreDBInstanceFromDBSnapshotResponse struct {
	*RestoreDBInstanceFromDBSnapshotOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// RestoreDBInstanceFromDBSnapshot request.
func (r *RestoreDBInstanceFromDBSnapshotResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
