// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package rdb provides the client and types for making API
// requests to rdb.
//
// See https://pfs.nifcloud.com/api/rdb/ for more information on this service.
//
// See rdb package documentation for more information.
// https://godoc.org/github.com/nifcloud/nifcloud-sdk-go/service/rdb/
//
// Using the Client
//
// To use rdb with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://godoc.org/github.com/nifcloud/nifcloud-sdk-go/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://godoc.org/github.com/nifcloud/nifcloud-sdk-go/nifcloud/#Config
//
// See the rdb client for more information on
// creating client for this service.
// https://godoc.org/github.com/nifcloud/nifcloud-sdk-go/service/rdb/#New
package rdb
