// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type DeleteMultiIpAddressGroupInput struct {
	_ struct{} `type:"structure"`

	// MultiIpAddressGroupId is a required field
	MultiIpAddressGroupId *string `locationName:"MultiIpAddressGroupId" type:"string" required:"true"`
}

// String returns the string representation
func (s DeleteMultiIpAddressGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DeleteMultiIpAddressGroupInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "DeleteMultiIpAddressGroupInput"}

	if s.MultiIpAddressGroupId == nil {
		invalidParams.Add(aws.NewErrParamRequired("MultiIpAddressGroupId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type DeleteMultiIpAddressGroupOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s DeleteMultiIpAddressGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDeleteMultiIpAddressGroup = "DeleteMultiIpAddressGroup"

// DeleteMultiIpAddressGroupRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DeleteMultiIpAddressGroupRequest.
//    req := client.DeleteMultiIpAddressGroupRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/DeleteMultiIpAddressGroup.htm
func (c *Client) DeleteMultiIpAddressGroupRequest(input *DeleteMultiIpAddressGroupInput) DeleteMultiIpAddressGroupRequest {
	op := &aws.Operation{
		Name:       opDeleteMultiIpAddressGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DeleteMultiIpAddressGroupInput{}
	}

	req := c.newRequest(op, input, &DeleteMultiIpAddressGroupOutput{})

	return DeleteMultiIpAddressGroupRequest{Request: req, Input: input, Copy: c.DeleteMultiIpAddressGroupRequest}
}

// DeleteMultiIpAddressGroupRequest is the request type for the
// DeleteMultiIpAddressGroup API operation.
type DeleteMultiIpAddressGroupRequest struct {
	*aws.Request
	Input *DeleteMultiIpAddressGroupInput
	Copy  func(*DeleteMultiIpAddressGroupInput) DeleteMultiIpAddressGroupRequest
}

// Send marshals and sends the DeleteMultiIpAddressGroup API request.
func (r DeleteMultiIpAddressGroupRequest) Send(ctx context.Context) (*DeleteMultiIpAddressGroupResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DeleteMultiIpAddressGroupResponse{
		DeleteMultiIpAddressGroupOutput: r.Request.Data.(*DeleteMultiIpAddressGroupOutput),
		response:                        &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DeleteMultiIpAddressGroupResponse is the response type for the
// DeleteMultiIpAddressGroup API operation.
type DeleteMultiIpAddressGroupResponse struct {
	*DeleteMultiIpAddressGroupOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DeleteMultiIpAddressGroup request.
func (r *DeleteMultiIpAddressGroupResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
