// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type NiftyUpdateAlarmInput struct {
	_ struct{} `type:"structure"`

	AlarmCondition AlarmConditionOfNiftyUpdateAlarmRequest `locationName:"AlarmCondition" type:"string" enum:"true"`

	Description *string `locationName:"Description" type:"string"`

	ElasticLoadBalancerName []string `locationName:"ElasticLoadBalancerName" type:"list"`

	ElasticLoadBalancerPort []int64 `locationName:"ElasticLoadBalancerPort" type:"list"`

	ElasticLoadBalancerProtocol []string `locationName:"ElasticLoadBalancerProtocol" type:"list"`

	EmailAddress []string `locationName:"EmailAddress" type:"list"`

	FunctionName FunctionNameOfNiftyUpdateAlarmRequest `locationName:"FunctionName" type:"string" enum:"true"`

	InstanceId []string `locationName:"InstanceId" type:"list"`

	LoadBalancerName []string `locationName:"LoadBalancerName" type:"list"`

	LoadBalancerPort []int64 `locationName:"LoadBalancerPort" type:"list"`

	Partition []string `locationName:"Partition" type:"list"`

	Rule []RequestRuleOfNiftyUpdateAlarm `locationName:"Rule" type:"list"`

	RuleName *string `locationName:"RuleName" type:"string"`

	RuleNameUpdate *string `locationName:"RuleNameUpdate" type:"string"`
}

// String returns the string representation
func (s NiftyUpdateAlarmInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyUpdateAlarmOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s NiftyUpdateAlarmOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyUpdateAlarm = "NiftyUpdateAlarm"

// NiftyUpdateAlarmRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyUpdateAlarmRequest.
//    req := client.NiftyUpdateAlarmRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/NiftyUpdateAlarm.htm
func (c *Client) NiftyUpdateAlarmRequest(input *NiftyUpdateAlarmInput) NiftyUpdateAlarmRequest {
	op := &aws.Operation{
		Name:       opNiftyUpdateAlarm,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyUpdateAlarmInput{}
	}

	req := c.newRequest(op, input, &NiftyUpdateAlarmOutput{})

	return NiftyUpdateAlarmRequest{Request: req, Input: input, Copy: c.NiftyUpdateAlarmRequest}
}

// NiftyUpdateAlarmRequest is the request type for the
// NiftyUpdateAlarm API operation.
type NiftyUpdateAlarmRequest struct {
	*aws.Request
	Input *NiftyUpdateAlarmInput
	Copy  func(*NiftyUpdateAlarmInput) NiftyUpdateAlarmRequest
}

// Send marshals and sends the NiftyUpdateAlarm API request.
func (r NiftyUpdateAlarmRequest) Send(ctx context.Context) (*NiftyUpdateAlarmResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyUpdateAlarmResponse{
		NiftyUpdateAlarmOutput: r.Request.Data.(*NiftyUpdateAlarmOutput),
		response:               &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyUpdateAlarmResponse is the response type for the
// NiftyUpdateAlarm API operation.
type NiftyUpdateAlarmResponse struct {
	*NiftyUpdateAlarmOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyUpdateAlarm request.
func (r *NiftyUpdateAlarmResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
