// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type DescribeRegionsInput struct {
	_ struct{} `type:"structure"`

	Filter []RequestFilterOfDescribeRegions `locationName:"Filter" type:"list"`

	RegionName []string `locationName:"RegionName" type:"list"`
}

// String returns the string representation
func (s DescribeRegionsInput) String() string {
	return nifcloudutil.Prettify(s)
}

type DescribeRegionsOutput struct {
	_ struct{} `type:"structure"`

	RegionInfo []RegionInfo `locationName:"regionInfo" locationNameList:"item" type:"list"`

	RequestId *string `locationName:"requestId" type:"string"`
}

// String returns the string representation
func (s DescribeRegionsOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDescribeRegions = "DescribeRegions"

// DescribeRegionsRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DescribeRegionsRequest.
//    req := client.DescribeRegionsRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/DescribeRegions.htm
func (c *Client) DescribeRegionsRequest(input *DescribeRegionsInput) DescribeRegionsRequest {
	op := &aws.Operation{
		Name:       opDescribeRegions,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DescribeRegionsInput{}
	}

	req := c.newRequest(op, input, &DescribeRegionsOutput{})

	return DescribeRegionsRequest{Request: req, Input: input, Copy: c.DescribeRegionsRequest}
}

// DescribeRegionsRequest is the request type for the
// DescribeRegions API operation.
type DescribeRegionsRequest struct {
	*aws.Request
	Input *DescribeRegionsInput
	Copy  func(*DescribeRegionsInput) DescribeRegionsRequest
}

// Send marshals and sends the DescribeRegions API request.
func (r DescribeRegionsRequest) Send(ctx context.Context) (*DescribeRegionsResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DescribeRegionsResponse{
		DescribeRegionsOutput: r.Request.Data.(*DescribeRegionsOutput),
		response:              &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DescribeRegionsResponse is the response type for the
// DescribeRegions API operation.
type DescribeRegionsResponse struct {
	*DescribeRegionsOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DescribeRegions request.
func (r *DescribeRegionsResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
