// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type NiftyDeletePrivateLanInput struct {
	_ struct{} `type:"structure"`

	NetworkId *string `locationName:"NetworkId" type:"string"`

	PrivateLanName *string `locationName:"PrivateLanName" type:"string"`
}

// String returns the string representation
func (s NiftyDeletePrivateLanInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyDeletePrivateLanOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s NiftyDeletePrivateLanOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyDeletePrivateLan = "NiftyDeletePrivateLan"

// NiftyDeletePrivateLanRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyDeletePrivateLanRequest.
//    req := client.NiftyDeletePrivateLanRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/NiftyDeletePrivateLan.htm
func (c *Client) NiftyDeletePrivateLanRequest(input *NiftyDeletePrivateLanInput) NiftyDeletePrivateLanRequest {
	op := &aws.Operation{
		Name:       opNiftyDeletePrivateLan,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyDeletePrivateLanInput{}
	}

	req := c.newRequest(op, input, &NiftyDeletePrivateLanOutput{})

	return NiftyDeletePrivateLanRequest{Request: req, Input: input, Copy: c.NiftyDeletePrivateLanRequest}
}

// NiftyDeletePrivateLanRequest is the request type for the
// NiftyDeletePrivateLan API operation.
type NiftyDeletePrivateLanRequest struct {
	*aws.Request
	Input *NiftyDeletePrivateLanInput
	Copy  func(*NiftyDeletePrivateLanInput) NiftyDeletePrivateLanRequest
}

// Send marshals and sends the NiftyDeletePrivateLan API request.
func (r NiftyDeletePrivateLanRequest) Send(ctx context.Context) (*NiftyDeletePrivateLanResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyDeletePrivateLanResponse{
		NiftyDeletePrivateLanOutput: r.Request.Data.(*NiftyDeletePrivateLanOutput),
		response:                    &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyDeletePrivateLanResponse is the response type for the
// NiftyDeletePrivateLan API operation.
type NiftyDeletePrivateLanResponse struct {
	*NiftyDeletePrivateLanOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyDeletePrivateLan request.
func (r *NiftyDeletePrivateLanResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
