// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type NiftyCreateNatTableInput struct {
	_ struct{} `type:"structure"`
}

// String returns the string representation
func (s NiftyCreateNatTableInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyCreateNatTableOutput struct {
	_ struct{} `type:"structure"`

	NatTable *NatTable `locationName:"natTable" type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`
}

// String returns the string representation
func (s NiftyCreateNatTableOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyCreateNatTable = "NiftyCreateNatTable"

// NiftyCreateNatTableRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyCreateNatTableRequest.
//    req := client.NiftyCreateNatTableRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/NiftyCreateNatTable.htm
func (c *Client) NiftyCreateNatTableRequest(input *NiftyCreateNatTableInput) NiftyCreateNatTableRequest {
	op := &aws.Operation{
		Name:       opNiftyCreateNatTable,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyCreateNatTableInput{}
	}

	req := c.newRequest(op, input, &NiftyCreateNatTableOutput{})

	return NiftyCreateNatTableRequest{Request: req, Input: input, Copy: c.NiftyCreateNatTableRequest}
}

// NiftyCreateNatTableRequest is the request type for the
// NiftyCreateNatTable API operation.
type NiftyCreateNatTableRequest struct {
	*aws.Request
	Input *NiftyCreateNatTableInput
	Copy  func(*NiftyCreateNatTableInput) NiftyCreateNatTableRequest
}

// Send marshals and sends the NiftyCreateNatTable API request.
func (r NiftyCreateNatTableRequest) Send(ctx context.Context) (*NiftyCreateNatTableResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyCreateNatTableResponse{
		NiftyCreateNatTableOutput: r.Request.Data.(*NiftyCreateNatTableOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyCreateNatTableResponse is the response type for the
// NiftyCreateNatTable API operation.
type NiftyCreateNatTableResponse struct {
	*NiftyCreateNatTableOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyCreateNatTable request.
func (r *NiftyCreateNatTableResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
