// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type NiftyDeregisterVpnGatewaysFromSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	// GroupName is a required field
	GroupName *string `locationName:"GroupName" type:"string" required:"true"`

	VpnGatewaySet []RequestVpnGatewaySet `locationName:"VpnGatewaySet" type:"list"`
}

// String returns the string representation
func (s NiftyDeregisterVpnGatewaysFromSecurityGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *NiftyDeregisterVpnGatewaysFromSecurityGroupInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "NiftyDeregisterVpnGatewaysFromSecurityGroupInput"}

	if s.GroupName == nil {
		invalidParams.Add(aws.NewErrParamRequired("GroupName"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type NiftyDeregisterVpnGatewaysFromSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	VpnGatewaySet []VpnGatewaySet `locationName:"vpnGatewaySet" locationNameList:"item" type:"list"`
}

// String returns the string representation
func (s NiftyDeregisterVpnGatewaysFromSecurityGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyDeregisterVpnGatewaysFromSecurityGroup = "NiftyDeregisterVpnGatewaysFromSecurityGroup"

// NiftyDeregisterVpnGatewaysFromSecurityGroupRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyDeregisterVpnGatewaysFromSecurityGroupRequest.
//    req := client.NiftyDeregisterVpnGatewaysFromSecurityGroupRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/NiftyDeregisterVpnGatewaysFromSecurityGroup.htm
func (c *Client) NiftyDeregisterVpnGatewaysFromSecurityGroupRequest(input *NiftyDeregisterVpnGatewaysFromSecurityGroupInput) NiftyDeregisterVpnGatewaysFromSecurityGroupRequest {
	op := &aws.Operation{
		Name:       opNiftyDeregisterVpnGatewaysFromSecurityGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyDeregisterVpnGatewaysFromSecurityGroupInput{}
	}

	req := c.newRequest(op, input, &NiftyDeregisterVpnGatewaysFromSecurityGroupOutput{})

	return NiftyDeregisterVpnGatewaysFromSecurityGroupRequest{Request: req, Input: input, Copy: c.NiftyDeregisterVpnGatewaysFromSecurityGroupRequest}
}

// NiftyDeregisterVpnGatewaysFromSecurityGroupRequest is the request type for the
// NiftyDeregisterVpnGatewaysFromSecurityGroup API operation.
type NiftyDeregisterVpnGatewaysFromSecurityGroupRequest struct {
	*aws.Request
	Input *NiftyDeregisterVpnGatewaysFromSecurityGroupInput
	Copy  func(*NiftyDeregisterVpnGatewaysFromSecurityGroupInput) NiftyDeregisterVpnGatewaysFromSecurityGroupRequest
}

// Send marshals and sends the NiftyDeregisterVpnGatewaysFromSecurityGroup API request.
func (r NiftyDeregisterVpnGatewaysFromSecurityGroupRequest) Send(ctx context.Context) (*NiftyDeregisterVpnGatewaysFromSecurityGroupResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyDeregisterVpnGatewaysFromSecurityGroupResponse{
		NiftyDeregisterVpnGatewaysFromSecurityGroupOutput: r.Request.Data.(*NiftyDeregisterVpnGatewaysFromSecurityGroupOutput),
		response: &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyDeregisterVpnGatewaysFromSecurityGroupResponse is the response type for the
// NiftyDeregisterVpnGatewaysFromSecurityGroup API operation.
type NiftyDeregisterVpnGatewaysFromSecurityGroupResponse struct {
	*NiftyDeregisterVpnGatewaysFromSecurityGroupOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyDeregisterVpnGatewaysFromSecurityGroup request.
func (r *NiftyDeregisterVpnGatewaysFromSecurityGroupResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
