// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type DeleteInstanceBackupRuleInput struct {
	_ struct{} `type:"structure"`

	InstanceBackupRuleId *string `locationName:"InstanceBackupRuleId" type:"string"`
}

// String returns the string representation
func (s DeleteInstanceBackupRuleInput) String() string {
	return nifcloudutil.Prettify(s)
}

type DeleteInstanceBackupRuleOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s DeleteInstanceBackupRuleOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDeleteInstanceBackupRule = "DeleteInstanceBackupRule"

// DeleteInstanceBackupRuleRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DeleteInstanceBackupRuleRequest.
//    req := client.DeleteInstanceBackupRuleRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/DeleteInstanceBackupRule.htm
func (c *Client) DeleteInstanceBackupRuleRequest(input *DeleteInstanceBackupRuleInput) DeleteInstanceBackupRuleRequest {
	op := &aws.Operation{
		Name:       opDeleteInstanceBackupRule,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DeleteInstanceBackupRuleInput{}
	}

	req := c.newRequest(op, input, &DeleteInstanceBackupRuleOutput{})

	return DeleteInstanceBackupRuleRequest{Request: req, Input: input, Copy: c.DeleteInstanceBackupRuleRequest}
}

// DeleteInstanceBackupRuleRequest is the request type for the
// DeleteInstanceBackupRule API operation.
type DeleteInstanceBackupRuleRequest struct {
	*aws.Request
	Input *DeleteInstanceBackupRuleInput
	Copy  func(*DeleteInstanceBackupRuleInput) DeleteInstanceBackupRuleRequest
}

// Send marshals and sends the DeleteInstanceBackupRule API request.
func (r DeleteInstanceBackupRuleRequest) Send(ctx context.Context) (*DeleteInstanceBackupRuleResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DeleteInstanceBackupRuleResponse{
		DeleteInstanceBackupRuleOutput: r.Request.Data.(*DeleteInstanceBackupRuleOutput),
		response:                       &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DeleteInstanceBackupRuleResponse is the response type for the
// DeleteInstanceBackupRule API operation.
type DeleteInstanceBackupRuleResponse struct {
	*DeleteInstanceBackupRuleOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DeleteInstanceBackupRule request.
func (r *DeleteInstanceBackupRuleResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
