// Code generated by smithy-go-codegen DO NOT EDIT.

package computing

import (
	"context"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/nifcloud/nifcloud-sdk-go/service/computing/types"
)

func (c *Client) NiftyUpdateRouterNetworkInterfaces(ctx context.Context, params *NiftyUpdateRouterNetworkInterfacesInput, optFns ...func(*Options)) (*NiftyUpdateRouterNetworkInterfacesOutput, error) {
	if params == nil {
		params = &NiftyUpdateRouterNetworkInterfacesInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "NiftyUpdateRouterNetworkInterfaces", params, optFns, c.addOperationNiftyUpdateRouterNetworkInterfacesMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*NiftyUpdateRouterNetworkInterfacesOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type NiftyUpdateRouterNetworkInterfacesInput struct {
	Agreement *bool

	NetworkInterface []types.RequestNetworkInterfaceOfNiftyUpdateRouterNetworkInterfaces

	NiftyReboot types.NiftyRebootOfNiftyUpdateRouterNetworkInterfacesRequest

	RouterId *string

	RouterName *string

	noSmithyDocumentSerde
}

type NiftyUpdateRouterNetworkInterfacesOutput struct {
	RequestId *string

	Return *bool

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationNiftyUpdateRouterNetworkInterfacesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	err = stack.Serialize.Add(&awsEc2query_serializeOpNiftyUpdateRouterNetworkInterfaces{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsEc2query_deserializeOpNiftyUpdateRouterNetworkInterfaces{}, middleware.After)
	if err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = awsmiddleware.AddClientRequestIDMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddComputeContentLengthMiddleware(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addRetryMiddlewares(stack, options); err != nil {
		return err
	}
	if err = addHTTPSignerV2Middleware(stack, options); err != nil {
		return err
	}
	if err = awsmiddleware.AddRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = awsmiddleware.AddRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addClientUserAgent(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opNiftyUpdateRouterNetworkInterfaces(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opNiftyUpdateRouterNetworkInterfaces(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "NiftyUpdateRouterNetworkInterfaces",
	}
}
