// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type DisassociateAddressInput struct {
	_ struct{} `type:"structure"`

	AssociationId *string `locationName:"AssociationId" type:"string"`

	NiftyReboot NiftyRebootOfDisassociateAddressRequest `locationName:"NiftyReboot" type:"string" enum:"true"`

	PrivateIpAddress *string `locationName:"PrivateIpAddress" type:"string"`

	PublicIp *string `locationName:"PublicIp" type:"string"`
}

// String returns the string representation
func (s DisassociateAddressInput) String() string {
	return nifcloudutil.Prettify(s)
}

type DisassociateAddressOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s DisassociateAddressOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDisassociateAddress = "DisassociateAddress"

// DisassociateAddressRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DisassociateAddressRequest.
//    req := client.DisassociateAddressRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/DisassociateAddress.htm
func (c *Client) DisassociateAddressRequest(input *DisassociateAddressInput) DisassociateAddressRequest {
	op := &aws.Operation{
		Name:       opDisassociateAddress,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DisassociateAddressInput{}
	}

	req := c.newRequest(op, input, &DisassociateAddressOutput{})

	return DisassociateAddressRequest{Request: req, Input: input, Copy: c.DisassociateAddressRequest}
}

// DisassociateAddressRequest is the request type for the
// DisassociateAddress API operation.
type DisassociateAddressRequest struct {
	*aws.Request
	Input *DisassociateAddressInput
	Copy  func(*DisassociateAddressInput) DisassociateAddressRequest
}

// Send marshals and sends the DisassociateAddress API request.
func (r DisassociateAddressRequest) Send(ctx context.Context) (*DisassociateAddressResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DisassociateAddressResponse{
		DisassociateAddressOutput: r.Request.Data.(*DisassociateAddressOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DisassociateAddressResponse is the response type for the
// DisassociateAddress API operation.
type DisassociateAddressResponse struct {
	*DisassociateAddressOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DisassociateAddress request.
func (r *DisassociateAddressResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
