// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type DeleteSslCertificateInput struct {
	_ struct{} `type:"structure"`

	// FqdnId is a required field
	FqdnId *string `locationName:"FqdnId" type:"string" required:"true"`
}

// String returns the string representation
func (s DeleteSslCertificateInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *DeleteSslCertificateInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "DeleteSslCertificateInput"}

	if s.FqdnId == nil {
		invalidParams.Add(aws.NewErrParamRequired("FqdnId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type DeleteSslCertificateOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s DeleteSslCertificateOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDeleteSslCertificate = "DeleteSslCertificate"

// DeleteSslCertificateRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DeleteSslCertificateRequest.
//    req := client.DeleteSslCertificateRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/DeleteSslCertificate.htm
func (c *Client) DeleteSslCertificateRequest(input *DeleteSslCertificateInput) DeleteSslCertificateRequest {
	op := &aws.Operation{
		Name:       opDeleteSslCertificate,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DeleteSslCertificateInput{}
	}

	req := c.newRequest(op, input, &DeleteSslCertificateOutput{})

	return DeleteSslCertificateRequest{Request: req, Input: input, Copy: c.DeleteSslCertificateRequest}
}

// DeleteSslCertificateRequest is the request type for the
// DeleteSslCertificate API operation.
type DeleteSslCertificateRequest struct {
	*aws.Request
	Input *DeleteSslCertificateInput
	Copy  func(*DeleteSslCertificateInput) DeleteSslCertificateRequest
}

// Send marshals and sends the DeleteSslCertificate API request.
func (r DeleteSslCertificateRequest) Send(ctx context.Context) (*DeleteSslCertificateResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DeleteSslCertificateResponse{
		DeleteSslCertificateOutput: r.Request.Data.(*DeleteSslCertificateOutput),
		response:                   &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DeleteSslCertificateResponse is the response type for the
// DeleteSslCertificate API operation.
type DeleteSslCertificateResponse struct {
	*DeleteSslCertificateOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DeleteSslCertificate request.
func (r *DeleteSslCertificateResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
