// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type NiftyUpdateSeparateInstanceRuleInput struct {
	_ struct{} `type:"structure"`

	SeparateInstanceRuleDescriptionUpdate *string `locationName:"SeparateInstanceRuleDescriptionUpdate" type:"string"`

	SeparateInstanceRuleName *string `locationName:"SeparateInstanceRuleName" type:"string"`

	SeparateInstanceRuleNameUpdate *string `locationName:"SeparateInstanceRuleNameUpdate" type:"string"`
}

// String returns the string representation
func (s NiftyUpdateSeparateInstanceRuleInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyUpdateSeparateInstanceRuleOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *string `locationName:"return" type:"string"`
}

// String returns the string representation
func (s NiftyUpdateSeparateInstanceRuleOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyUpdateSeparateInstanceRule = "NiftyUpdateSeparateInstanceRule"

// NiftyUpdateSeparateInstanceRuleRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyUpdateSeparateInstanceRuleRequest.
//    req := client.NiftyUpdateSeparateInstanceRuleRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/NiftyUpdateSeparateInstanceRule.htm
func (c *Client) NiftyUpdateSeparateInstanceRuleRequest(input *NiftyUpdateSeparateInstanceRuleInput) NiftyUpdateSeparateInstanceRuleRequest {
	op := &aws.Operation{
		Name:       opNiftyUpdateSeparateInstanceRule,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyUpdateSeparateInstanceRuleInput{}
	}

	req := c.newRequest(op, input, &NiftyUpdateSeparateInstanceRuleOutput{})

	return NiftyUpdateSeparateInstanceRuleRequest{Request: req, Input: input, Copy: c.NiftyUpdateSeparateInstanceRuleRequest}
}

// NiftyUpdateSeparateInstanceRuleRequest is the request type for the
// NiftyUpdateSeparateInstanceRule API operation.
type NiftyUpdateSeparateInstanceRuleRequest struct {
	*aws.Request
	Input *NiftyUpdateSeparateInstanceRuleInput
	Copy  func(*NiftyUpdateSeparateInstanceRuleInput) NiftyUpdateSeparateInstanceRuleRequest
}

// Send marshals and sends the NiftyUpdateSeparateInstanceRule API request.
func (r NiftyUpdateSeparateInstanceRuleRequest) Send(ctx context.Context) (*NiftyUpdateSeparateInstanceRuleResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyUpdateSeparateInstanceRuleResponse{
		NiftyUpdateSeparateInstanceRuleOutput: r.Request.Data.(*NiftyUpdateSeparateInstanceRuleOutput),
		response:                              &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyUpdateSeparateInstanceRuleResponse is the response type for the
// NiftyUpdateSeparateInstanceRule API operation.
type NiftyUpdateSeparateInstanceRuleResponse struct {
	*NiftyUpdateSeparateInstanceRuleOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyUpdateSeparateInstanceRule request.
func (r *NiftyUpdateSeparateInstanceRuleResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
