// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type UpdateSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	GroupDescriptionUpdate *string `locationName:"GroupDescriptionUpdate" type:"string"`

	GroupLogFilterBroadcast *bool `locationName:"GroupLogFilterBroadcast" type:"boolean"`

	GroupLogFilterNetBios *bool `locationName:"GroupLogFilterNetBios" type:"boolean"`

	GroupLogLimitUpdate *int64 `locationName:"GroupLogLimitUpdate" type:"integer"`

	// GroupName is a required field
	GroupName *string `locationName:"GroupName" type:"string" required:"true"`

	GroupNameUpdate *string `locationName:"GroupNameUpdate" type:"string"`

	GroupRuleLimitUpdate *int64 `locationName:"GroupRuleLimitUpdate" type:"integer"`
}

// String returns the string representation
func (s UpdateSecurityGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *UpdateSecurityGroupInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "UpdateSecurityGroupInput"}

	if s.GroupName == nil {
		invalidParams.Add(aws.NewErrParamRequired("GroupName"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type UpdateSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s UpdateSecurityGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opUpdateSecurityGroup = "UpdateSecurityGroup"

// UpdateSecurityGroupRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using UpdateSecurityGroupRequest.
//    req := client.UpdateSecurityGroupRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/UpdateSecurityGroup.htm
func (c *Client) UpdateSecurityGroupRequest(input *UpdateSecurityGroupInput) UpdateSecurityGroupRequest {
	op := &aws.Operation{
		Name:       opUpdateSecurityGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &UpdateSecurityGroupInput{}
	}

	req := c.newRequest(op, input, &UpdateSecurityGroupOutput{})

	return UpdateSecurityGroupRequest{Request: req, Input: input, Copy: c.UpdateSecurityGroupRequest}
}

// UpdateSecurityGroupRequest is the request type for the
// UpdateSecurityGroup API operation.
type UpdateSecurityGroupRequest struct {
	*aws.Request
	Input *UpdateSecurityGroupInput
	Copy  func(*UpdateSecurityGroupInput) UpdateSecurityGroupRequest
}

// Send marshals and sends the UpdateSecurityGroup API request.
func (r UpdateSecurityGroupRequest) Send(ctx context.Context) (*UpdateSecurityGroupResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &UpdateSecurityGroupResponse{
		UpdateSecurityGroupOutput: r.Request.Data.(*UpdateSecurityGroupOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// UpdateSecurityGroupResponse is the response type for the
// UpdateSecurityGroup API operation.
type UpdateSecurityGroupResponse struct {
	*UpdateSecurityGroupOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// UpdateSecurityGroup request.
func (r *UpdateSecurityGroupResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
