// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type NiftyDeleteNatTableInput struct {
	_ struct{} `type:"structure"`

	// NatTableId is a required field
	NatTableId *string `locationName:"NatTableId" type:"string" required:"true"`
}

// String returns the string representation
func (s NiftyDeleteNatTableInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *NiftyDeleteNatTableInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "NiftyDeleteNatTableInput"}

	if s.NatTableId == nil {
		invalidParams.Add(aws.NewErrParamRequired("NatTableId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type NiftyDeleteNatTableOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s NiftyDeleteNatTableOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyDeleteNatTable = "NiftyDeleteNatTable"

// NiftyDeleteNatTableRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyDeleteNatTableRequest.
//    req := client.NiftyDeleteNatTableRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/NiftyDeleteNatTable.htm
func (c *Client) NiftyDeleteNatTableRequest(input *NiftyDeleteNatTableInput) NiftyDeleteNatTableRequest {
	op := &aws.Operation{
		Name:       opNiftyDeleteNatTable,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyDeleteNatTableInput{}
	}

	req := c.newRequest(op, input, &NiftyDeleteNatTableOutput{})

	return NiftyDeleteNatTableRequest{Request: req, Input: input, Copy: c.NiftyDeleteNatTableRequest}
}

// NiftyDeleteNatTableRequest is the request type for the
// NiftyDeleteNatTable API operation.
type NiftyDeleteNatTableRequest struct {
	*aws.Request
	Input *NiftyDeleteNatTableInput
	Copy  func(*NiftyDeleteNatTableInput) NiftyDeleteNatTableRequest
}

// Send marshals and sends the NiftyDeleteNatTable API request.
func (r NiftyDeleteNatTableRequest) Send(ctx context.Context) (*NiftyDeleteNatTableResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyDeleteNatTableResponse{
		NiftyDeleteNatTableOutput: r.Request.Data.(*NiftyDeleteNatTableOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyDeleteNatTableResponse is the response type for the
// NiftyDeleteNatTable API operation.
type NiftyDeleteNatTableResponse struct {
	*NiftyDeleteNatTableOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyDeleteNatTable request.
func (r *NiftyDeleteNatTableResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
