// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/nifcloud/nifcloud-sdk-go/internal/nifcloudutil"
)

type RebootInstancesInput struct {
	_ struct{} `type:"structure"`

	Force *bool `locationName:"Force" type:"boolean"`

	// InstanceId is a required field
	InstanceId []string `locationName:"InstanceId" type:"list" required:"true"`

	NiftyIsBios *bool `locationName:"NiftyIsBios" type:"boolean"`

	Tenancy []string `locationName:"Tenancy" type:"list"`

	UserData *RequestUserData `locationName:"UserData" type:"structure"`
}

// String returns the string representation
func (s RebootInstancesInput) String() string {
	return nifcloudutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *RebootInstancesInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "RebootInstancesInput"}

	if s.InstanceId == nil {
		invalidParams.Add(aws.NewErrParamRequired("InstanceId"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type RebootInstancesOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Return *bool `locationName:"return" type:"boolean"`
}

// String returns the string representation
func (s RebootInstancesOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opRebootInstances = "RebootInstances"

// RebootInstancesRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using RebootInstancesRequest.
//    req := client.RebootInstancesRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api/rest/RebootInstances.htm
func (c *Client) RebootInstancesRequest(input *RebootInstancesInput) RebootInstancesRequest {
	op := &aws.Operation{
		Name:       opRebootInstances,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &RebootInstancesInput{}
	}

	req := c.newRequest(op, input, &RebootInstancesOutput{})

	return RebootInstancesRequest{Request: req, Input: input, Copy: c.RebootInstancesRequest}
}

// RebootInstancesRequest is the request type for the
// RebootInstances API operation.
type RebootInstancesRequest struct {
	*aws.Request
	Input *RebootInstancesInput
	Copy  func(*RebootInstancesInput) RebootInstancesRequest
}

// Send marshals and sends the RebootInstances API request.
func (r RebootInstancesRequest) Send(ctx context.Context) (*RebootInstancesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &RebootInstancesResponse{
		RebootInstancesOutput: r.Request.Data.(*RebootInstancesOutput),
		response:              &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// RebootInstancesResponse is the response type for the
// RebootInstances API operation.
type RebootInstancesResponse struct {
	*RebootInstancesOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// RebootInstances request.
func (r *RebootInstancesResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
