// Code generated by smithy-go-codegen DO NOT EDIT.

package computing

import (
	"context"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) NiftyAssociateRouteTableWithElasticLoadBalancer(ctx context.Context, params *NiftyAssociateRouteTableWithElasticLoadBalancerInput, optFns ...func(*Options)) (*NiftyAssociateRouteTableWithElasticLoadBalancerOutput, error) {
	if params == nil {
		params = &NiftyAssociateRouteTableWithElasticLoadBalancerInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "NiftyAssociateRouteTableWithElasticLoadBalancer", params, optFns, c.addOperationNiftyAssociateRouteTableWithElasticLoadBalancerMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*NiftyAssociateRouteTableWithElasticLoadBalancerOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type NiftyAssociateRouteTableWithElasticLoadBalancerInput struct {

	// This member is required.
	ElasticLoadBalancerId *string

	// This member is required.
	RouteTableId *string

	noSmithyDocumentSerde
}

type NiftyAssociateRouteTableWithElasticLoadBalancerOutput struct {
	RequestId *string

	Return *bool

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationNiftyAssociateRouteTableWithElasticLoadBalancerMiddlewares(stack *middleware.Stack, options Options) (err error) {
	err = stack.Serialize.Add(&awsEc2query_serializeOpNiftyAssociateRouteTableWithElasticLoadBalancer{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsEc2query_deserializeOpNiftyAssociateRouteTableWithElasticLoadBalancer{}, middleware.After)
	if err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = awsmiddleware.AddClientRequestIDMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddComputeContentLengthMiddleware(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addRetryMiddlewares(stack, options); err != nil {
		return err
	}
	if err = addHTTPSignerV2Middleware(stack, options); err != nil {
		return err
	}
	if err = awsmiddleware.AddRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = awsmiddleware.AddRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addClientUserAgent(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addOpNiftyAssociateRouteTableWithElasticLoadBalancerValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opNiftyAssociateRouteTableWithElasticLoadBalancer(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opNiftyAssociateRouteTableWithElasticLoadBalancer(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "NiftyAssociateRouteTableWithElasticLoadBalancer",
	}
}
