// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package dns

type ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSets string

// Enum values for ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSets
const (
	ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsCreate ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "CREATE"
	ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsDelete ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "DELETE"
)

func (enum ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValue() (string, error) {
	return string(enum), nil
}

func (enum ActionOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValueBuf(b []byte) ([]byte, error) {
	b = b[0:0]
	return append(b, enum...), nil
}

type FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSets string

// Enum values for FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSets
const (
	FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsPrimary   FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "PRIMARY"
	FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsSecondary FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "SECONDARY"
)

func (enum FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValue() (string, error) {
	return string(enum), nil
}

func (enum FailoverOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValueBuf(b []byte) ([]byte, error) {
	b = b[0:0]
	return append(b, enum...), nil
}

type ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets string

// Enum values for ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets
const (
	ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsHttp  ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "HTTP"
	ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsHttps ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "HTTPS"
	ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsTcp   ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "TCP"
)

func (enum ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValue() (string, error) {
	return string(enum), nil
}

func (enum ProtocolOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValueBuf(b []byte) ([]byte, error) {
	b = b[0:0]
	return append(b, enum...), nil
}

type TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets string

// Enum values for TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets
const (
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsNs    TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "NS"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsA     TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "A"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsAaaa  TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "AAAA"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsCname TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "CNAME"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsMx    TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "MX"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsTxt   TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "TXT"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsPtr   TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "PTR"
	TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSetsLbr   TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets = "LBR"
)

func (enum TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValue() (string, error) {
	return string(enum), nil
}

func (enum TypeOfChangeResourceRecordSetsRequestForChangeResourceRecordSets) MarshalValueBuf(b []byte) ([]byte, error) {
	b = b[0:0]
	return append(b, enum...), nil
}

type TypeOfListResourceRecordSetsRequest string

// Enum values for TypeOfListResourceRecordSetsRequest
const (
	TypeOfListResourceRecordSetsRequestNs    TypeOfListResourceRecordSetsRequest = "NS"
	TypeOfListResourceRecordSetsRequestA     TypeOfListResourceRecordSetsRequest = "A"
	TypeOfListResourceRecordSetsRequestAaaa  TypeOfListResourceRecordSetsRequest = "AAAA"
	TypeOfListResourceRecordSetsRequestCname TypeOfListResourceRecordSetsRequest = "CNAME"
	TypeOfListResourceRecordSetsRequestMx    TypeOfListResourceRecordSetsRequest = "MX"
	TypeOfListResourceRecordSetsRequestTxt   TypeOfListResourceRecordSetsRequest = "TXT"
	TypeOfListResourceRecordSetsRequestPtr   TypeOfListResourceRecordSetsRequest = "PTR"
	TypeOfListResourceRecordSetsRequestLbr   TypeOfListResourceRecordSetsRequest = "LBR"
)

func (enum TypeOfListResourceRecordSetsRequest) MarshalValue() (string, error) {
	return string(enum), nil
}

func (enum TypeOfListResourceRecordSetsRequest) MarshalValueBuf(b []byte) ([]byte, error) {
	b = b[0:0]
	return append(b, enum...), nil
}
