name: Integration
on:
  push:
    branches:
      - main
      - feature/update-go
  pull_request:
env:
  GOPROXY: https://proxy.golang.org
  NIFCLOUD_ACCESS_KEY_ID: ${{ secrets.NIFCLOUD_ACCESS_KEY_ID }}
  NIFCLOUD_SECRET_ACCESS_KEY: ${{ secrets.NIFCLOUD_SECRET_ACCESS_KEY }}
  NIFCLOUD_STORAGE_ACCESS_KEY_ID: ${{ secrets.NIFCLOUD_STORAGE_ACCESS_KEY_ID }}
  NIFCLOUD_STORAGE_SECRET_ACCESS_KEY: ${{ secrets.NIFCLOUD_STORAGE_SECRET_ACCESS_KEY }}
jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24' ]
    name: Go ${{ matrix.go }} integration-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Integration tests
        run: make integration
